src/admin/models.py
# -*- coding: utf-8 -*-

class Tutor:
  def __init__(self, info):
    self.info = info
  
  @property
  def id(self):
    return self.info.get("_id")
  
  @property
  def tutorid(self):
    return self.info.get("tutorid")
  
  @property
  def name(self):
    return self.info.get("name")
  
  @property
  def mobile(self):
    return self.info.get("mobile")
  
  @property
  def email(self):
    return self.info.get("email")
  
  @property
  def facebook(self):
    return self.info.get("facebook")
  
  @property
  def descriptions(self):
    return self.info.get("descriptions")
  
  @property
  def urlimg(self):
    return self.info.get("urlimg")
  
  @property
  def adults(self):
    return self.info.get("adults")
  
  @property
  def college(self):
    return self.info.get("college")
  
  @property
  def subjects(self):
    return self.info.get("subjects", [])
  
class Classrm:
  def __init__(self, info):
    self.info = info
    
  @property
  def id(self):
    return self.info.get("_id")

src/learning/models.py
# -*- coding: utf-8 -*-
import db


class Questions():
  def __init__(self, info):
    self.info = info
  
  @property
  def id(self):
    if self.info:
      return self.info.get("_id")
  
  @property
  def contents(self):
    if self.info:
      return self.info.get("contents")
  
  @property
  def tags(self):
    if self.info:
      return self.info.get("tags")
  
  @property
  def userid(self):
    if self.info:
      return self.info.get("userid")
    
  @property
  def answers(self):
    if self.info:
      return self.info.get("answers", [])
  
  @property
  def topic(self):
    if self.info:
      return self.info.get("topic")
  
  @property
  def like(self):
    if self.info:
      return self.info.get("like", [])
  
  @property
  def dislike(self):
    if self.info:
      return self.info.get("dislike", [])
  
  @property
  def followers(self):
    if self.info:
      return self.info.get("followers", [])
    
class Answers():
  def __init__(self, info):
    self.info = info
  
  @property
  def id(self):
    if self.info:
      return self.info.get("_id")
  
  @property
  def contents(self):
    if self.info:
      return self.info.get("contents")
  
  @property
  def userid(self):
    if self.info:
      return self.info.get("userid")
  
  @property
  def like(self):
    if self.info:
      return self.info.get("like", [])
    
  @property
  def dislike(self):
    if self.info:
      return self.info.get("dislike", [])

src/frontend/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField, SubmitField, SelectField, validators, ValidationError, PasswordField, BooleanField

class ContactForm(Form):
    name = TextField(u"Họ Tên:")
    email = TextField(u"Email:", [validators.Required(u"Địa chỉ Email không hợp lệ!"), validators.Email(u"Địa chỉ Email không hợp lệ!")])
    mobile = TextField(u"Số ĐT:")
    classroom = SelectField(u'Lớp:', choices=[('lop1', u'Lớp 1'), ('lop2', u'Lớp 2'), ('lop3', u'Lớp 3'), ('lop4', u'Lớp 4'),
                                              ('lop5', u'Lớp 5'), ('lop6', u'Lớp 6'), ('lop7', u'Lớp 7'), ('lop8', u'Lớp 8'),
                                              ('lop9', u'Lớp 9'), ('lop10', u'Lớp 10'), ('lop11', u'Lớp 11'), ('lop12', u'Lớp 12'), ('khac', u'Khác')])
    subject = TextField(u"Môn học:")
    message = TextAreaField(u"Yêu cầu:")
    submit = SubmitField(u"Gửi")
    
class RegisterTutorForm(Form):
    name = TextField(u"Họ Tên:", [validators.Required(u"Bạn chưa nhập tên")])
    email = TextField(u"Email:", [validators.Required(u"Bạn chưa nhập địa chỉ mail")])
    mobile = TextField(u"Số ĐT:", [validators.Required(u"Bạn chưa nhập số ĐT")])
    fbacc = TextField(u"Facebook:", [validators.Required(u"Bạn chưa nhập tài khoản Facebook")])
    college = TextField(u"Trường ĐH đang học:", [validators.Required(u"Bạn chưa nhập tên trường ĐH bạn đang học")])
    highschool = TextField(u"Trường THPT đã học:", [validators.Required(u"Bạn chưa nhập tên trường THPT bạn đã học")])
    subject = TextField(u"Môn học đăng kí dạy:", [validators.Required(u"Bạn chưa nhập môn học đăng kí dạy")])
    descriptions = TextAreaField(u"Thành tích, kinh nghiệm:", [validators.Required(u"Bạn chưa cung cấp thông tin thành tích, kinh nghiệm gia sư của bạn")])
    submit = SubmitField(u"Gửi")

    
    

src/users/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField, SubmitField, SelectField, validators, ValidationError, PasswordField, BooleanField

class LoginForm(Form):
    username = TextField(u"Username:")
    password = PasswordField(u"Password:")
    rememberme = BooleanField(u"Remember Me")
    submit = SubmitField(u"Login")

class RegisterForm(Form):
    name = TextField(u"Your name:")
    email = TextField(u"Email:")
    password = PasswordField(u"Password:")
    submit = SubmitField(u"Signup") 

src/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

src/admin/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, flash, url_for, redirect, session
from users.models import User
import db, api
admin = Blueprint("admin", __name__,
                  template_folder="templates", static_folder="static")

@admin.route("/lsadmin", methods=["GET", "POST"])
@api.login_required
def lsadmin():
    return redirect("/dashboard")

@admin.route("/dashboard", methods=["GET", "POST"])
@api.login_required
def index():
    title = "Dashboard"
    count_tutors = db.count_all_tutors()
    count_class = db.count_all_class()
    count_class_empty = db.count_class_empty()
    classinfo = db.get_all_class()
    tutors = db.get_all_tutors()
    return render_template("admin/dashboard.html", title=title, count_tutors=count_tutors, tutors=tutors,
                           count_class=count_class, count_class_empty=count_class_empty, classinfo=classinfo)
    
@admin.route("/createclass", methods=["GET", "POST"])
@api.login_required
def createclass():
    message = ""
    if request.method == "POST":
      classid = request.form.get("classid")
      subject = request.form.get("subject")
      level = request.form.get("level")
      parents = request.form.get("parents")
      mobile = request.form.get("mobile")
      address = request.form.get("address")
      fee = request.form.get("fee")
      if not "K" in fee:
        fee += "K"
      pay = request.form.get("pay")
      if not "%" in pay:
        pay += "%"
      require = request.form.get("require")
      status = request.form.get("status")
      time = request.form.get("time")
      tutorid = request.form.get("tutorid")
      note = request.form.get("note")
      count = db.count_all_class()
      _id = 1301 + count
      if subject == "Toán":
        urlimg = "img/class/math.jpg"
        namesubj = "Toán học"
      elif subject == "Văn":
        namesubj = "Văn học"
        urlimg = "img/class/van.jpg"
      elif subject == "Anh":
        namesubj = "Tiếng Anh"
        urlimg = "img/class/english.jpg"
      elif subject == "Lý":
        namesubj = "Vật lý"
        urlimg = "img/class/physical.jpg"
      elif subject == "Hóa":
        namesubj = "Hóa học"
        urlimg = "img/class/chemistry.jpg"
      data = {"_id":int(_id), "classid":classid, "subject":namesubj, "level":level, "parents":parents, "address":address, "note":note,
              "mobile":mobile, "fee":fee, "pay":pay, "require":require, "status":status, "urlimg":urlimg, "tutorid":tutorid, "time":time}
      db.add_new_class(data)
      message = "Add new class successful."
      return render_template("admin/createclass.html", message=message)
    else:
      title = "Create Class"
      return render_template("admin/createclass.html", title=title)

@admin.route("/addtutor", methods=["GET", "POST"])
@api.login_required
def addtutor():
  if request.method == "POST":
    tutorid = request.form.get("tutorid")
    name = request.form.get("name")
    subjects = request.form.getlist("subjects")
    email = request.form.get("email")
    mobile = request.form.get("mobile")
    facebook = request.form.get("facebook")
    college = request.form.get("college")
    descriptions = request.form.get("descriptions")
    adults = request.form.get("adults")
    clc = request.form.get("clc")
    if clc == "Yes":
      quality = True
    else:
      quality = False
    count = db.count_all_tutors()
    _id = 1301 + count
    urlimg = "img/tutor/%s.jpg" %tutorid
    data = {"_id":int(_id), "tutorid":tutorid, "name":name, "subjects":subjects, "email":email, "mobile":mobile, "urlimg":urlimg,
            "facebook":facebook, "college":college, "descriptions":descriptions, "adults":adults, "quality":quality}
    db.add_new_tutors(data)
    message = "Add new tutor successful."
    return render_template("admin/addtutor.html", message=message)
  else:
    title = "Add Tutor"
    return render_template("admin/addtutor.html", title=title)

@admin.route("/editclass", methods=["GET", "POST"])
@api.login_required
def editclass():
  if request.method == "POST":
    classid = request.form.get("classid")
    status = request.form.get("status")
    tutorid = request.form.get("tutorid")
    data = {"status":status, "tutorid":tutorid}    
    db.update_class_info(classid, data)
    return redirect("/dashboard")

src/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

src/frontend/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, session, flash, redirect, url_for
import db, api
from forms import ContactForm, RegisterTutorForm



frontend = Blueprint('frontend', __name__,
                        template_folder='templates', static_folder='static')

PER_PAGE = 5

@frontend.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html")

@frontend.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()
    
    if request.method == "POST":
        if form.validate() == False:
            flash(u'All fields are required.')
            return render_template('contact.html', form=form)
        else:
            # msg = Message(form.subject.data, sender='contact@example.com', recipients=['your_email@example.com'])
            msg = u"""
              *** Sent from Website giasuchuyenlamson.com ***
              Name: %s <%s>
              ĐT: %s
              Môn học: %s , Lớp: %s
              Yêu cầu: %s              
              """ % (form.name.data, form.email.data, form.mobile.data, form.subject.data, form.classroom.data, form.message.data)
            api.Send_mail(msg)
            return render_template("contact.html", success=True, form=form)
    elif request.method == "GET":
        return render_template("contact.html", form=form)

@frontend.route("/tutors", defaults={'page': 1})
@frontend.route("/tutors/<int:page>")
def tutor(page):
    count = db.count_all_tutors()
    tutors = db.get_tutors_for_page(page, PER_PAGE)
    pagination = api.Pagination(page, PER_PAGE, count)
    return render_template("tutors.html", tutors=tutors, pagination=pagination)


@frontend.route("/news", methods=["GET", "POST"])
def news():
    news = db.get_all_news()
    return render_template("news.html", news=news)

@frontend.route("/registertutor", methods=["GET", "POST"])
def registertutor():
    form = RegisterTutorForm()
    
    if request.method == "POST":
        if form.validate() == False:
            flash(u"Bạn chưa điền đầy đủ thông tin.")
            return render_template("registertutor.html", form=form)
        else:
            msg = u"""
              *** Sent From Website giasuchuyenlamson.com ***
              Name: %s <%s>
              ĐT: %s
              Facebook: %s
              Trường ĐH: %s
              THPT: %s
              Môn học: %s
              Thành tích, Kinh nghiệm: %s
            """ % (form.name.data, form.email.data, form.mobile.data, form.fbacc.data,
                  form.college.data, form.highschool.data, form.subject.data, form.descriptions.data)
            api.Send_mail(msg)
            return render_template("registertutor.html", success=True, form=form)
    elif request.method == "GET":
        return render_template("registertutor.html", form=form)

@frontend.route("/about", methods=["GET", "POST"])
def about():
    return render_template("about.html")

@frontend.route("/aboutlamson", methods=["GET", "POST"])
def aboutls():
    return render_template("aboutls.html")

@frontend.route("/document", methods=["GET", "POST"])
def document():
#     documents = db.get_new_documents()
#     return render_template("document.html", documents = documents)
    return render_template("learning.html")

@frontend.route("/displaydoc/<title>", methods=["GET", "POST"])
def displaydoc(title):
    document = db.get_document_bytitle(title)
    return render_template("displaydoc.html", document=document)

@frontend.route("/learning", methods=["GET", "POST"])
def learning():
    return render_template("learning.html")

@frontend.route("/price", methods=["GET", "POST"])
def price():
    return render_template("price.html")

@frontend.route("/classinfo", defaults={'page': 1})
@frontend.route("/classinfo/<int:page>")
def classinfo(page):
    count = db.count_all_class()
    classinfo = db.get_classinfo_for_page(page, 4)
    pagination = api.Pagination(page, 4, count)
    return render_template("classinfo.html", classinfo=classinfo, pagination=pagination)

@frontend.route("/registerclass", methods=["GET", "POST"])
def registerclass():
  if request.method == "POST":
    classid = request.form.get("classid")
    mobile = request.form.get("mobilerc")
    email = request.form.get("emailrc")
    tutor = db.get_tutor(mobile)
    if tutor:
      error = False
      message = u"""
      *** Sent from website ***
      %s (%s) đăng kí nhận lớp %s
      Email liên hệ: %s
      """ %(tutor.get("name"), tutor.get("tutorid"), classid, email)
      api.Send_mail(message)
      msg = "Bạn gửi đăng kí thành công. Chúng tôi sẽ xem xét đăng kí của bạn. Nếu bạn được nhận lớp, chúng tôi sẽ liên hệ với bạn theo số điện thoại và email mà bạn đã cung cấp."
    else:
      error = True
      msg = "Số điện thoại của bạn không hợp lệ hoặc do bạn chưa đăng kí làm gia sư của CLB."
      
  return render_template("notify.html", msg=msg, error=error)

src/learning/__init__.py
# -*- coding: utf-8 -*-

from .views import learning

src/learning/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, flash, redirect, url_for
import db, api



learning = Blueprint('learning', __name__,
                        template_folder='templates', static_folder='static')

@learning.route("/newfeed", methods=["GET", "POST"])
@api.login_required
def newfeed():
  return render_template("learning/base.html")

src/users/__init__.py
# -*- coding: utf-8 -*-

from .views import users

src/users/views.py
# -*- coding : utf-8 -*-
from flask import (Blueprint, render_template, request, redirect,
                   make_response, flash, session)
from forms import LoginForm
from uuid import uuid4
import hashlib
import db


users = Blueprint("users", __name__, template_folder='templates',
                  static_folder="static")

@users.route("/login", methods=["GET", "POST"])
def login():
    message = ""
    if request.method == "POST":
        username = request.form.get('username',
                                  request.args.get('username'))
        password = request.form.get('password')
        
        if not username or not password:
            message = "Please fill all the fields."
            return render_template("login.html", message=message)
        if username == "admin":
          session_id = db.sign_in(username, password)
        else:
          session_id = db.login(username, password)
        if not session_id:
            message = "Username or Password is invaild."
            return render_template("login.html", message=message)
        
        session['session_id'] = session_id
        if username == "admin":
          return redirect("/dashboard")
        else: 
          return redirect("/learningpage")
    else:
        return render_template("login.html", message=message)

@users.route("/logout", methods=["GET", "POST"])
def logout():
  session_id = session.get('session_id')
  if session_id:
    db.logout(session_id)
    session.pop('session_id')
  return redirect('/')

src/templates/contact.html
{% from "macros/_form.html" import render_form %}

{% extends "index.html" %}
  
{% block content %}
<div class="content">
   <div class="container">
      <div class="row">
         <div class="span12">
            
            <!-- Contact starts -->
            
            <div class="contact">
               <div class="row">
                  <div class="span12">
                  
                     <!-- Contact hero -->
                     <div class="hero">
                        <!-- Title. Don't forget the <span> tag -->
                        <h3><span class="color">Liên hệ:</span></h3>
                        <!-- para -->
                        <p>Câu lạc bộ gia sư THPT chuyên Lam Sơn - Thanh Hóa trân trọng cảm ơn các bậc phụ huynh, các em học sinh đã quan tâm và lựa chọn chúng tôi.
							Để được hỗ trợ tốt hơn, vui lòng liên hệ trực tiếp với chúng tôi:</p>
                     </div>
                     <!-- Contact -->
                     
                     <div class="contact">
                        <div class="row">
                           <div class="span12">
                              
                           </div>
                        </div>
                        <div class="row">
                           <div class="span6">
                              <div class="cwell">
                                 <!-- Contact form -->
                                    <h5>Liên hệ tìm gia sư:</h5>
                                    <hr />
                                    {% if success %}
    									<div class="flash alert alert-success">Bạn đã gửi yêu cầu thành công.</div>
 
  									{% else %}
                                    	{% for message in form.email.errors %}
  											<div class="flash alert alert-error">{{ message }}</div>
										{% endfor %}
									{% endif %}
                                    <div class="form">
                                      <!-- Contact form start (not working)-->
                                  	  {{ render_form(url_for('frontend.contact'), form)}}
                                      <!-- Contact form end -->
                                    </div>
                                    <hr />
                                    
                                       <div class="csoci">  
                                           <!-- Social media icons -->
                                           <strong>Liên lạc qua:</strong>
                                           <div class="social">
                                                <a href="http://on.fb.me/1355Voh"><i class="icon-facebook"></i></a>
                                                <a href="http://bit.ly/YqZcGE"><i class="icon-google-plus"></i></a>
                                                
                                           </div>
                                       </div>
                                 </div>
                           </div>
                           <div class="span6">
                                 <div class="cwell">
                              <!-- Google maps -->
                              <div class="gmap">
                                 <!-- Google Maps. Replace the below iframe with your Google Maps embed code -->
                                 <iframe height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/?ie=UTF8&amp;t=m&amp;ll=21.024795,105.800593&amp;spn=0.003505,0.00456&amp;z=17&amp;output=embed"></iframe>
                              </div>
                              
                                    <!-- Address section -->
                                       <h5>Địa chỉ:</h5>
                                       <hr />
                                       <div class="address">
                                           <address>
                                              <!-- Company name -->
                                              <strong>CLB Gia sư chuyên Lam Sơn.</strong><br>
                                              <!-- Address -->
                                              P606, N09, Trung Kính<br>
                                              Q. Cầu Giấy, Hà Nội<br>
                                              <!-- Phone number -->
                                              <abbr title="Phone">M:</abbr> 0947046064.
                                           </address>
                                            
                                           <address>
                                              <!-- Name -->
                                              <strong>Full Name:</strong><br>
                                              <!-- Email -->
                                              <p>Mr: Hoàng Tuấn Anh</p>
                                              <a>giasuchuyenlamson@gmail.com</a>
                                           </address>
                                       </div>
                                 </div>
                           </div>
                        </div>
                        
                     </div>
                     
                  </div>
               </div>
            </div>
                         
            <!-- Service ends -->            
         </div>
      </div>
   </div>
</div>   


{% endblock %}

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="google-site-verification" content="UOO-M31mNvQKIjjydb_BQu9XykaNY6ndCvw_iPhZ60E" />
  <meta name="alexaVerifyID" content="TTMaNrfqkgG3cbteLPcj1aNc_8M" />
  <meta charset="utf-8">
  <!-- Title -->
  <title>Gia Sư Chất lượng cao - Truyền nhiệt huyết - Tạo đam mê</title>
  <!-- Description, Keywords -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="Huy Le Viet">

  <!-- Stylesheets -->
  <link href="{{ url_for('static', filename='style/bootstrap.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='style/slider.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='style/prettyPhoto.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style/font-awesome.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style/reveal.css') }}">
  <!--[if IE 7]>
  <link rel="stylesheet" href="style/font-awesome-ie7.css">
  <![endif]-->		
  <link href="{{ url_for('static', filename='style/style.css') }}" rel="stylesheet">
<!-- Color Stylesheet - orange, blue, pink, brown, red or green-->
  <link href="{{ url_for('static', filename='style/blue.css') }}" rel="stylesheet">    
  <link href="{{ url_for('static', filename='style/bootstrap-responsive.css') }}" rel="stylesheet">
  
  <!-- HTML5 Support for IE -->
  <!--[if lt IE 9]>
  <script src="js/html5shim.js"></script>
  <![endif]-->

  <!-- Favicon -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

</head>

<body>

<!-- Header starts -->

<header>
   <div class="container">
      <div class="row">
         <div class="span4">
            <!-- Logo and site link -->
            <div class="logo">
               <a href="index.html"><img src="{{ url_for('static', filename='img/logo.png') }}"></a>
            </div>
         </div>
         <div class="span3 offset5">
            <div class="list">
               <!-- Add your phone number here -->
               <div class="phone">
                  <i class="icon-phone"></i> Phone: 0947046064
               </div>
               <hr />
               <!-- Add your email id here -->
               <div class="email">
                  <i class="icon-envelope-alt"></i> Email: giasuchuyenlamson@gmail.com
               </div>
               <hr />
               <!-- Add your address here -->
               <div class="address">
                  <i class="icon-home"></i> Address: P606, N09, Trung Kính, Cầu Giấy, HN
               </div>
            </div>
         </div>
      </div>
   </div>
</header>

<!-- Header ends -->

<!-- Navigation Starts -->

<!-- Note down the syntax before editing. It is the default twitter bootstrap navigation -->

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            Menu
          </a>
          <div class="nav-collapse collapse">
            <!-- Navigation links starts here -->
            <ul class="nav">
              <!-- Main menu -->
              <li><a href="{{ url_for('frontend.home') }}">Home</a></li>      
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Giới thiệu <b class="caret"></b></a>
                <!-- Submenus -->
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('frontend.aboutls') }}">Trường THPT Chuyên Lam Sơn</a></li>
                  <li><a href="{{ url_for('frontend.about') }}">CLB Gia sư Chuyên Lam Sơn</a></li>                                
                </ul>
              </li>
              <li><a href="{{ url_for('frontend.price') }}">Học phí tham khảo</a></li>
              <li class="dropdown">
              	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Gia Sư <b class="caret"></b></a>
              	<ul class="dropdown-menu">
              		<li><a href="{{ url_for('frontend.tutor') }}">Gia sư tiêu biểu</a></li>
              		<li><a href="{{ url_for('frontend.registertutor') }}">Đăng ký làm gia sư</a></li>
              	</ul>
              </li>
              <li><a href="{{ url_for('frontend.classinfo') }}">Danh sách lớp mới</a></li>
              <li><a href="{{ url_for('frontend.contact') }}">Liên hệ</a></li>
            </ul>
            
            <ul class="nav pull-right">
           	  <li><a href="{{ url_for('frontend.document') }}">Tài Liệu</a></li>
           	  <li><a href="http://hoctap.giasuchuyenlamson.com">Góc Học Tập</a></li>
			</ul>
            
          </div>
        </div>
      </div>
    </div>
    
<!-- Navigation Ends -->   

<!-- Content strats -->
{% block content %}
{% endblock %}
<!-- Content ends --> 
	
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">      
      <div class="span12"><p class="copy">
      <!-- Copyright information. You can remove my site link. -->
               Copyright &copy; 2013 LamSon Team. All rights reserved.</p></div>
    </div>
  </div>
</footer>		
  <!-- JS -->
  <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script> -->
  <script  type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/jquery.isotope.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/jquery.prettyPhoto.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/filter.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/jquery.tweet.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/jquery.cslider.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/modernizr.custom.28468.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/custom.js') }}"></script>
  <script  type="text/javascript" src="{{ url_for('static', filename='js/jcarousellite_1.0.1c4.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/admin/jquery.reveal.js') }}"></script>
  <script type="text/javascript">
			$(function() {
			
				$('#da-slider').cslider({
					autoplay	: true,
					interval : 6000
				});
				
				$(".jcarouse").jCarouselLite({  // Lấy class của ul và gọi hàm jCarouselLite() trong thư viện
					//vertical: true,				// chạy theo chiều dọc
					hoverPause:true,			// Hover vào nó sẽ dừng lại
					visible: 3,					// Số bài viết cần hiện
					auto:500,					// Tự động scroll
					speed:4500					// Tốc độ scroll
				});
				
				$(".jcarousels").jCarouselLite({  // Lấy class của ul và gọi hàm jCarouselLite() trong thư viện
					vertical: true,				// chạy theo chiều dọc
					hoverPause:true,			// Hover vào nó sẽ dừng lại
					visible: 3,					// Số bài viết cần hiện
					auto:500,					// Tự động scroll
					speed:4500					// Tốc độ scroll
				});
			
			});
		</script>
  <script>
  	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  	ga('create', 'UA-41182160-1', 'giasuchuyenlamson.com');
  	ga('send', 'pageview');

	</script>	
</body>
</html>